name: publish

on:
  push:
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
      dry_run:
        description: "Dry run"
        required: false
        type: boolean
        default: true

jobs:
  config:
    name: Configure workflow
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.config.outputs.version }}
      dry_run: ${{ steps.config.outputs.dry_run }}
    steps:
      - id: config
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "dry_run=${{ github.event.inputs.dry_run }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
            echo "dry_run=false" >> $GITHUB_OUTPUT
          fi

  publish:
    environment: production
    needs: config
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          ref: refs/tags/v${{ needs.config.outputs.version }}

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v3

      - run: pnpm install

      - run: pnpm build

      - run: /bin/bash set-version.sh v${{ needs.config.outputs.version }}

      - run: pnpm publish --no-git-checks --access public
        if: ${{ needs.config.outputs.dry_run == 'false' }}
